export enum FileTypes {
  Folder = '',
  JavaScript = 'js',
  TypeScript = 'ts',
  HTML = 'html',
  CSS = 'css',
  JSON = 'json',
  XML = 'xml',
  Markdown = 'md',
  YAML = 'yaml',
  SQL = 'sql',
  Java = 'java',
  Python = 'py',
  Ruby = 'rb',
  CSharp = 'cs',
  CPlusPlus = 'cpp',
  Swift = 'swift',
  Go = 'go',
  PHP = 'php',
  ShellScript = 'sh',
  BatchScript = 'bat',
  PowerShellScript = 'ps1',
  TypeScriptDeclaration = 'd.ts',
  CHeader = 'h',
  CPPHeader = 'hpp',
  ObjectiveC = 'm',
  Kotlin = 'kt',
  Scala = 'scala',
  Perl = 'pl',
  Rust = 'rs',
  VBScript = 'vbs',
  RScript = 'R',
  Lua = 'lua',
  CoffeeScript = 'coffee',
  Dart = 'dart',
  Assembly = 'asm',
  Other = 'other'
}
export const fileExtensions: { [key: string]: FileTypes } = {
  'js': FileTypes.JavaScript,
  'ts': FileTypes.TypeScript,
  'html': FileTypes.HTML,
  'css': FileTypes.CSS,
  'json': FileTypes.JSON,
  'xml': FileTypes.XML,
  'md': FileTypes.Markdown,
  'yaml': FileTypes.YAML,
  'sql': FileTypes.SQL,
  'java': FileTypes.Java,
  'py': FileTypes.Python,
  'rb': FileTypes.Ruby,
  'cs': FileTypes.CSharp,
  'cpp': FileTypes.CPlusPlus,
  'swift': FileTypes.Swift,
  'go': FileTypes.Go,
  'php': FileTypes.PHP,
  'sh': FileTypes.ShellScript,
  'bat': FileTypes.BatchScript,
  'ps1': FileTypes.PowerShellScript,
  'd.ts': FileTypes.TypeScriptDeclaration,
  'h': FileTypes.CHeader,
  'hpp': FileTypes.CPPHeader,
  'm': FileTypes.ObjectiveC,
  'kt': FileTypes.Kotlin,
  'scala': FileTypes.Scala,
  'pl': FileTypes.Perl,
  'rs': FileTypes.Rust,
  'vbs': FileTypes.VBScript,
  'R': FileTypes.RScript,
  'lua': FileTypes.Lua,
  'coffee': FileTypes.CoffeeScript,
  'dart': FileTypes.Dart,
  'asm': FileTypes.Assembly,
  'other': FileTypes.Other,
};